server:
  port: 8080

spring:
  application:
    name: newsseug

  profiles:
    default: local

  docker:
    compose:
      lifecycle-management: start_only

  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
      tracing:
        include-parameter-values: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace